
#Setting up API Keys
# Azure AI Search
AZURE_SEARCH_SERVICE_ENDPOINT = ''
AZURE_SEARCH_ADMIN_KEY = ''
AZURE_SEARCH_INDEX_NAME = 'resume'
AZURE_SEARCH_SEMANTIC_CONFIG_NAME = ''
embedding_field_name = 'embedding'
NUMBER_OF_NEAR_NEIGHBORS = '2'
#  OpenAI

OPENAI_API_KEY=''

