NUMBER_OF_RESULTS_TO_RETURN = 5
#Setting up API Keys
# Azure AI Search
AZURE_SEARCH_SERVICE_ENDPOINT = ''
AZURE_SEARCH_ADMIN_KEY = ''
AZURE_SEARCH_INDEX_NAME = 'resume'
AZURE_SEARCH_SEMANTIC_CONFIG_NAME = ''
embedding_field_name = 'embedding'
NUMBER_OF_NEAR_NEIGHBORS = '3'
#  OpenAI

OPENAI_API_KEY=''
OPENAI_DEPLOYMENT_ID = 'gpt-3.5-turbo'

#AZURE OPEN AI
AZURE_OPENAI_ENDPOINT = ''
AZURE_OPENAI_KEY= ''
AZURE_OPENAI_DEPLOYMENT_ID = 'gpt-3.5-turbo-0125'